### ISSUE TITLE
Consolidar varios CSVs en uno

### ISSUE THREAD

**Issue by pilimayora** [datosgobar/data-cleaner#3]
Más específicamente, me refiero al caso donde hay un archivo por provincia (voy a asumir que no es un caso aislado el que me estoy encontrando y que vale la pena agregar esto al data cleaner).
La idea sería consolidar todos los archivos en uno, agregando una columna "Provincia" a ser completada tal vez por el nombre del archivo o algún otro parámetro a discutir.

**Comment by abenassi** [comment]
Welcome back @pilimayora !! Se extrañaban tus issues. Me parece un caso de
uso relevante, hoy lo vemos
