### ISSUE TITLE
Agregar capacidad de leer un SHP y transformarlo a CSV (geojson)

### ISSUE THREAD

**Issue by abenassi** [datosgobar/data-cleaner#43]
Hoy el `data-cleaner` sólo admite la interpretación de archivos CSV que internamente se convierten a DataFrame de pandas para ofrecer una serie de reglas de limpieza y transformación.

El archivo limpio y transformado se puede guardar nuevamente en CSV mediante el método DataCleaner.save().

Se busca **agregar la capacidad del objeto DataCleaner de leer/entender un SHP** para poder aplicar las mismas reglas de transformación y limpieza disponible para usar en un CSV, y luego transformar el formato guardando los datos geográficos en un CSV.

Convertir un SHP en CSV implica mayormente trabajar en la creación de una columna **geom** en el CSV que contenga las figuras geométricas que en el caso del SHP se guardan en un formato no tabular específico, en forma de un string **geojson**.

*Research previa*: El uso de [GeoPandas](http://geopandas.org/) como alternativa a [Pandas](http://pandas.pydata.org/) para que el objeto `DataCleaner` lea SHP es probablemente la mejor posibilidad a explorar. Permite mantener la interfaz interna construida sobre la base de Pandas para las reglas de transformación y limpieza, y permite usar funcionalidades geográficas para leer un SHP y convertirlo a GEOJSON.

La experiencia de uso de la librería buscada sería: 

```python
from data_cleaner import DataCleaner

input_path = "samples/provincias/provincias.shp"
output_path = "samples/provincias.csv"

dc = DataCleaner(input_path)
dc.save(output_path)
```

*Otros requerimientos*: revisar la interfaz y el estilo de implementación actual de `DataCleaner` para que el desarrollo vaya en línea con la idea de la librería en general. Crear tests para la nueva funcionalidad siguiendo el estilo de los tests ya implementados para otras funcionalidades.

**Comment by abenassi** [comment]
@pilimayora ahí creé el issue para encarar con @arperoni sobre conversión de shapefiles a CSV con geojson legibles por CKAN. Avisame qué clarificaciones harían falta sobre esto o cuándo podría juntarme con Artur para ver dudas y demás.

**Comment by arperoni** [comment]
**Fecha estimada de entrega:** viernes 1/9.

**Comment by abenassi** [comment]
+ Parametrizar la columna de salida de las geometrias en `DataCleaner.save()` y poner `geojson` por default
