### ISSUE TITLE
Agregar capacidad de transformar un SHP en otros formatos geográficos abiertos

### ISSUE THREAD

**Issue by abenassi** [datosgobar/data-cleaner#44]
*Dependencias*: este issue requiere la implementación previa de #43 

Una vez que `DataCleaner` es capaz de entender internamente un SHP y guardarlo en CSV (geojson), se puede plantear fácilmente la capacidad de transformarlo a otros formatos:

- [x] **GEOJSON**
- [x] **KML**

La experiencia buscada descansa en que para el usuario esta transformación sea transparente, manejada por `DataCleaner` sólo con la lectura de las extensiones de entrada y salida:

```python
from data_cleaner import DataCleaner

input_path = "samples/provincias/provincias.shp"
output_path = "samples/provincias.geojson"
output_path = "samples/provincias.kml"

dc = DataCleaner(input_path)
dc.save(output_path)
```

**Comment by arperoni** [comment]
Para transdformar a formato KML, se usó una solución basada en https://stackoverflow.com/questions/36222857/convert-geodataframe-polygons-to-kml-file.
