### ISSUE TITLE
Soporte para utilizar data-cleaner con python3

### ISSUE THREAD

**Issue by iheredia** [datosgobar/data-cleaner#58]
> ¿Cuál es el comportamiento que esperabas y cuál fue el comportamiento recibido? 

Poder utilizar el data-cleaner con python3 

> ¿Cuáles son los pasos para reproducir el bug?

Teniendo python 3 y virtualenv instalado:
```bash
$ virtualenv -p python3 venv
$ . venv/bin/activate
$ pip install data-cleaner
```

> Detalles del contexto: ¿qué sistema operativo, qué versión de navegador estás usando, por ejemplo?

```bash
$ uname -a # version del sistema operativo (mac os)
Darwin ARAR013089 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
$ python --version
Python 3.6.3
$ pip --version
pip 18.1 from /Users/iheredia/personal/test_data-cleaner/venv/lib/python3.6/site-packages/pip (python 3.6)
```

> ¿Tenés algún stack trace o captura de pantalla? Adjuntalo.  

```
$ pip install data_cleaner
Collecting data_cleaner
  Using cached https://files.pythonhosted.org/packages/87/41/e4fe93373f2897bde6d5c8fe8036b08b96ad7e6307be29d8da22a63c7030/data-cleaner-0.1.18.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hs/cx3bmdc53ng9m4vgwp9yqcyw35lmdf/T/pip-install-bxbhc_10/data-cleaner/setup.py", line 21, in <module>
        shutil.copy("README.md", os.path.join("docs", "README.md"))
      File "/Users/iheredia/personal/test_data-cleaner/venv/lib/python3.6/shutil.py", line 241, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/Users/iheredia/personal/test_data-cleaner/venv/lib/python3.6/shutil.py", line 121, in copyfile
        with open(dst, 'wb') as fdst:
    FileNotFoundError: [Errno 2] No such file or directory: 'docs/README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hs/cx3bmdc53ng9m4vgwp9yqcyw35lmdf/T/pip-install-bxbhc_10/data-cleaner/
```

**Comment by abenassi** [comment]
Nacho, cómo andás??

Qué raro esto no me pasa a mí, pero parece simplemente agregar la carpeta
docs al MANIFEST.in, no?

**Comment by abenassi** [comment]
@federicotdn @iheredia ahí limpié un poco y agregué ambas cosas, hay una versión 0.1.20 que se instala bien de cero con python 2 pero que falla con python 3 (a mí al menos) al intentar instalar `pyproj`. En esa estoy más bien perdido...

**Comment by federicotdn** [comment]
En Python 3.5.2 me funciona la instalación de `pyproj`.

**Comment by federicotdn** [comment]
Con 3.6.4 también me funciona pero con 3.7.2 no, debe estar relacionado a este issue: https://github.com/jswhit/pyproj/issues/136. Por el momento podríamos apuntar a 3.6.X o versiones anteriores.

**Comment by iheredia** [comment]
Buenas,

Volví a probar instalar el data cleaner y si bien ahora no tengo el error que puse en el primer comentario de este issue, tampoco estoy pudiendo lograr usarlo.
El contexto es el mismo que al principio del issue (misma version de python, pip y OS)
```bash
$ pip install data_cleaner # se instala ok
$ python
>>> import data_cleaner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/iheredia/personal/test/venv/lib/python3.6/site-packages/data_cleaner/__init__.py", line 4, in <module>
    from data_cleaner import DataCleaner
ImportError: cannot import name 'DataCleaner'
```

**Comment by iheredia** [comment]
@abenassi falta hacer una publicación del repo con los nuevos cambios para py3, no?

**Comment by abenassi** [comment]
@iheredia ahí liberé la versión 0.1.21 que ya es python 3!

**Comment by iheredia** [comment]
👏👏👏
