### ISSUE TITLE
Definir una licencia para el repo

### ISSUE THREAD

**Issue by iheredia** [datosgobar/data-cleaner#63]
El repo actualmente tiene 2 licencias diferentes. 
Hay un [archivo LICENSE con una licencia GNU GPL](https://github.com/datosgobar/data-cleaner/blob/master/LICENSE) y un [archivo LICENSE.md con licencia MIT](https://github.com/datosgobar/data-cleaner/blob/master/LICENSE.md)

[What are the key differences between the GNU General Public license and the MIT License?
 ](https://www.quora.com/What-are-the-key-differences-between-the-GNU-General-Public-license-and-the-MIT-License)

**Comment by abenassi** [comment]
Estamos yendo con MIT para todos los casos!
